version = 1
SPDX-PackageName = "Xide"
SPDX-PackageSupplier = "Organization: Progmasoft"
SPDX-PackageDownloadLocation = "https://github.com/Progmasoft/xide"

[[annotations]]
path = ["xit/CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Progmasoft <support@progmasoft.com>"
SPDX-License-Identifier = "MPL-2.0 WITH AdditionRef-Progmasoft-Exception-1.0"
